sudo: true
dist: bionic
os: linux
language: bash
# Handle git submodules yourself
git:
    submodules: false
services:
  - docker
before_install:
  - git config --global url."https://github.com/".insteadOf git@github.com:
  - git submodule update --init --recursive
  - sed -i 's/#INSERT_HERE/COPY . \/mod_event_redis/g' .devcontainer/Dockerfile
  - cat .devcontainer/Dockerfile
  - docker build -t mod_event_redis -f .devcontainer/Dockerfile .
  - docker run mod_event_redis make -C /mod_event_redis
script:
  -  docker run -i mod_event_redis bash -c "cd /mod_event_redis && make && ls"
