sudo: true
dist: bionic
os: linux
language: bash
# Handle git submodules yourself
git:
    submodules: false
services:
  - docker
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - sed -i 's/#INSERT_HERE/COPY . \/mod_event_redis/g' .devcontainer/Dockerfile
  - cat .devcontainer/Dockerfile
  - docker build -t mod_event_redis -f .devcontainer/Dockerfile .
script:
  -  docker run -i mod_event_redis bash -c "cd /mod_event_redis/lib/cpp_redis && mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release && make && make install && cd /mod_event_redis && make && ls"
